// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB968_N0JYcjj73xj4xgK8omwBfPf6pmWI',
    appId: '1:268276293681:web:01f5e2af266550165a7510',
    messagingSenderId: '268276293681',
    projectId: 'notebook-165f4',
    authDomain: 'notebook-165f4.firebaseapp.com',
    storageBucket: 'notebook-165f4.appspot.com',
    measurementId: 'G-NLKZMXXKYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmb44FCVY2dTT6zhjlRuSP0NJjChAnx3g',
    appId: '1:268276293681:android:446741c579d230d35a7510',
    messagingSenderId: '268276293681',
    projectId: 'notebook-165f4',
    storageBucket: 'notebook-165f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8qbyQp1gXUv30vXazSxQ_-2ELNq1gQzQ',
    appId: '1:268276293681:ios:71b57d680ab28fbb5a7510',
    messagingSenderId: '268276293681',
    projectId: 'notebook-165f4',
    storageBucket: 'notebook-165f4.appspot.com',
    iosClientId:
        '268276293681-4j5em6tqsd1ak8o03hpvd0df3ll6lpbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8qbyQp1gXUv30vXazSxQ_-2ELNq1gQzQ',
    appId: '1:268276293681:ios:71b57d680ab28fbb5a7510',
    messagingSenderId: '268276293681',
    projectId: 'notebook-165f4',
    storageBucket: 'notebook-165f4.appspot.com',
    iosClientId:
        '268276293681-4j5em6tqsd1ak8o03hpvd0df3ll6lpbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteBook',
  );
}
